# Generated by Django 3.2 on 2021-04-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckInModel',
        ),
    ]
