# Generated by Django 3.2 on 2021-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin_form', '0002_delete_checkinmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('age', models.IntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=250)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default=None, max_length=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'CASH'), ('Credit Card', 'CREDIT CARD'), ('Debit Card', 'DEBIT CARD'), ('UPI', 'UPI')], default=None, max_length=20)),
                ('file_field', models.FileField(default=None, upload_to='')),
                ('checkin', models.DateField(default=None)),
                ('checkout', models.DateField(default=None)),
                ('room_allocated', models.CharField(choices=[('1001(1 bed)', '1001'), ('1002(2 beds)', '1002'), ('1003(3 beds)', '1003'), ('1004(4 beds)', '1004'), ('2001(1 bed)', '2001'), ('2002(2 beds)', '2002')], default=None, max_length=100)),
                ('additional_choices', models.CharField(choices=[('Air Conditioned', 'AC'), ('Free Pick-Up', 'PICK UP'), ('Mini Fridge', 'MINIFRIDGE'), ('Gym', 'GYM')], default=None, max_length=100)),
            ],
        ),
    ]
