# Generated by Django 3.2 on 2021-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_form', '0003_checkinmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmodel',
            name='address',
            field=models.TextField(default=None, max_length=250),
        ),
    ]
