# Generated by Django 3.2 on 2021-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_form', '0004_alter_checkinmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmodel',
            name='additional_choices',
            field=models.CharField(choices=[('AC', 'Air Conditioned'), ('PICK UP', 'Free Pick-Up'), ('MINIFRIDGE', 'Mini Fridge'), ('GYM', 'Gym')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='file_field',
            field=models.ImageField(db_column='Poi_Img', upload_to=''),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='room_allocated',
            field=models.CharField(choices=[('1001', '1001(1 bed)'), ('1002', '1002(2 beds)'), ('1003', '1003(3 beds)'), ('1004', '1004(4 beds)'), ('2001', '2001(1 bed)'), ('2002', '2002(2 beds)')], default=None, max_length=100),
        ),
    ]
