# Generated by Django 3.2 on 2021-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_form', '0006_alter_checkinmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmodel',
            name='additional_choices',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
